### ISSUE TITLE
Parser NotImplemented exception after exactly 15 ticks

### ISSUE THREAD

**Issue by Sotolotl** [StatsHelix/demoinfo#157]
I've tried parsing several demos from games for the last few days, but every one of them throws a System.NotImplemented exception when calling parser.ParseToEnd(). By calling ParseNextTick() in a while loop and counting the iterations, it seems like it's always failing to parse the 16th tick.

I've only been able to try demos of games for the last day or two, unfortunately, I don't have any older demos available to test.

Has anyone else seen this issue before?

Full stack trace below.

   at DemoInfo.DP.Handler.PacketEntitesHandler.PropertyCollector..ctor(Entity underlying, IList'1 capture)
   at DemoInfo.DP.Handler.PacketEntitesHandler.ReadEnterPVS(IBitStream reader, Int32 id, DemoParser parser)
   at DemoInfo.DP.Handler.PacketEntitesHandler.Apply(PacketEntities packetEntities, IBitStream reader, DemoParser parser)
   at DemoInfo.PacketEntities.Parse(IBitStream bitstream, DemoParser parser)
   at DemoInfo.DP.DemoPacketParser.ParsePacket(IBitStream bitstream, DemoParser demo)
   at DemoInfo.DemoParser.ParseDemoPacket()
   at DemoInfo.DemoParser.ParseTick()
   at DemoInfo.DemoParser.ParseNextTick()
   at StatisticsGenerator.MainClass.Main(String[] args) in demostatistics-generator-master\StatisticsGenerator\Program.cs:line 211`

**Comment by YorVeX** [comment]
Are you sure you're using the latest version of this library from this Github? I had the same error message when using an older version but demo parsing works again after updating to the latest source files from here and compiling it myself.

While parsing I am still getting some errors like "Unknown weapon. sensorgrenade" and "Unknown weapon. snowball" but other than that it's working fine and at the end of the parsing cycle I get all  player's ranks (which is what I am using this library for).

Maybe you got it through NuGet? That hasn't been updated since November 2015.

**Comment by Sotolotl** [comment]
Yeah, I realised this and forgot to close the thread. I was using the NuGet package, if anyone else has this issue then make sure you're using the latest source from GH!

Thanks, YorVeX
