### ISSUE TITLE
Invalid File-Type - expecting HL2DEMO

### ISSUE THREAD

**Issue by shark25361** [StatsHelix/demoinfo#170]
I'm trying to parse the .dems from https://www.hltv.org/matches/2350388/vitality-vs-natus-vincere-esl-pro-league-season-14 using a build from DemoInfo with signed assemblies disabled. However, the following code: 
`DemoParser parser = new DemoParser(File.OpenRead(args[0]));`
`parser.ParseHeader();`
causes the following error:
Unhandled Exception: System.IO.InvalidDataException: Invalid File-Type - expecting HL2DEMO
   at DemoInfo.DemoParser.ParseHeader()
   at csgo_highlights.Program.getKills(DemoParser parser)
   at csgo_highlights.Program.Main(String[] args)

**Comment by moritzuehling** [comment]
Did you unzip/unrar the file from hltv.org?
